spring:
  datasource:
#    url: jdbc:h2:tcp://localhost/~/wecrm
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
    url: jdbc:mysql://127.0.0.1:3306/wecrm
    username: root
    password: 3wndeowkd#
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  #      show_sql: true
        format_sql: true
logging.level:
  org.hibernate.SQL: debug